CRM-Challenge/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'customers#index'

  get 'customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetized'
  get 'customers/missing_email', to: 'customers#missing_email', as: 'missing_email'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CRM-Challenge/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

CRM-Challenge/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CRM-Challenge/app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  validates :name, :phone, presence: true
  validates :name, uniqueness: true
end

CRM-Challenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

CRM-Challenge/app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:name)
  end

  def missing_email
    @customers = Customer.where(email: [nil, ''])
  end
end

CRM-Challenge/app/helpers/application_helper.rb
module ApplicationHelper
end

CRM-Challenge/app/helpers/customers_helper.rb
module CustomersHelper
end

CRM-Challenge/app/views/customers/_customer.html.erb
<div class="column">
  <div class="card">
    <h2><b><%= customer.name %></b></h2>
    <%= image_tag(customer.image, size: "600x400") %>
    <div class="container">
      <p><%= customer.phone %></p>
      <p><%= customer.email %></p>
      <p><strong>Notes:</strong> <%= customer.notes %></p>
    </div>
  </div>
</div>

CRM-Challenge/app/views/customers/alphabetized.html.erb
<h1>Alphabetized Customers</h1>

<div class="row">
  <%= render partial: 'customers/customer',
             collection: @customers %>
</div>

CRM-Challenge/app/views/customers/index.html.erb
<h1>All Customers</h1>

<div class="row">
  <%= render partial: 'customers/customer',
             collection: @customers %>
</div>

CRM-Challenge/app/views/customers/missing_email.html.erb
<h1>Customers Missing Emails</h1>

<div class="row">
  <%= render partial: 'customers/customer',
             collection: @customers %>
</div>

CRM-Challenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRMChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to 'All Customers', root_path %></li>
      <li><%= link_to 'Alphabetized Customers', alphabetized_path %></li>
      <li><%= link_to 'Missing Email Customers', missing_email_path %></li>
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>